<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHvj48zl\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHvj48zl/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerHvj48zl.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerHvj48zl\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerHvj48zl\appProdProjectContainer(array(
    'container.build_hash' => 'Hvj48zl',
    'container.build_id' => 'e0ba93a6',
    'container.build_time' => 1520552941,
));
