<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSzxvzza\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSzxvzza/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSzxvzza.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSzxvzza\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerSzxvzza\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Szxvzza',
    'container.build_id' => 'e9e9e7d8',
    'container.build_time' => 1520551417,
));
