<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIbxieo2\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIbxieo2/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIbxieo2.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIbxieo2\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIbxieo2\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ibxieo2',
    'container.build_id' => '5ec346c7',
    'container.build_time' => 1520595806,
));
